{{{
#!python
** Mercurial version (1.8.4).  TortoiseHg version (2.0.5)
** Command: --nofork log --listfile C:\DOCUME~1\Work\LOCALS~1\Temp\THG5CF.tmp
** CWD: D:\Projects\ITP_WEB\itp\application
** Extensions loaded: fixfrozenexts, onsub, graphlog, convert, purge, rebase, mq, transplant
** Python version: 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)]
** Windows version: (5, 1, 2600, 2, 'Service Pack 3')
** Processor architecture: x86
** Qt-4.7.1 PyQt-4.8.3
Recoverable runtime error (stderr):
Exception in thread visualdiff:
Traceback (most recent call last):
  File "threading.pyo", line 532, in __bootstrap_inner
  File "threading.pyo", line 484, in run
  File "tortoisehg\hgqt\visdiff.pyo", line 355, in dodiffwrapper
  File "tortoisehg\hgqt\visdiff.pyo", line 341, in dodiff
  File "tortoisehg\hgqt\visdiff.pyo", line 144, in launchtool
  File "subprocess.pyo", line 623, in __init__
  File "subprocess.pyo", line 833, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 82-83: ordinal not in range(128)


}}}